@extends('layouts.global')
@section('content')
    @include('components.navbar')
    @include('components.hero')
    @include('components.about')
    @include('components.depart')
    @include('components.dokumentasi')
    @include('components.footer')
@endsection
